sudo: false

language: node_js

notifications:
  email: false

script: "npm run $TASK"

env: TASK=test

matrix:
  include:
  - node_js: '0.12'
    before_install: npm -g i npm@2

  - node_js: 'iojs'
    before_install: npm -g i npm@2

  - node_js: 'stable'
    before_install: npm -g i npm@3
