sudo: false

language: node_js

notifications:
  email: false

script: "npm run $TASK"

matrix:
  include:
  - node_js: '0.12'
    env: TASK=test
  - node_js: 'iojs-v1.0.0'
    env: TASK=test
  - node_js: 'iojs-v2.0.0'
    env: TASK=test
  - node_js: 'iojs'
    env: TASK=test
